apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu-deployment
spec:
  selector:
    matchLabels:
      app: MenuItemListing
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: MenuItemLisiting
    spec:
      containers:
      - name: MenuItemLisiting
        image: practisecheck.azurecr.io/menulistimage:latest
        ports:
        - containerPort: 8080

